POST http://localhost:8001/v1/person_detection
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./pexels-allan-mas-5368927.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--