# API Configuration
api:
  endpoint: "/v1/person_detection"
  host: "0.0.0.0" 
  port: 8000

# Output Configuration
output:
  folder: "./outputs"

# Database Configuration 
database:
  host: "db"
  port: 5432
  name: "people_counter"
  user: "postgres"
  password: "postgres"
